### PR TITLE
Backport fix from D7 module.

### PR DESCRIPTION
**Pull request by universalhandle**
Replaces extremely inefficient (and inappropriate) API call for group_contact with one for group entity.

### CODE REVIEW

**Comment by universalhandle** [comment]
@jackrabbithanna: here's some more D6 action for you.

Jenkins says there was one failing check, but I don't see any in the report and the console says:

> PR test not allowed for 6.x-master

... so I guess human review will have to do.

**Comment by jackrabbithanna** [comment]
Jenkins please retest this

**Comment by jackrabbithanna** [comment]
Jenkins test this please

**Comment by jackrabbithanna** [comment]
oh yeah I forgot d6 and d8 don't have tests. I've reviewed and tested the code.
Recommend Merging

**Comment by jackrabbithanna** [comment]
Merging #514

**Pull request merged**
