### PR TITLE
Refactor v2 api calls CRM-9794

### PR DESCRIPTION
**Pull request by colemanw**
---
- CRM-9794: Remove API v2
  http://issues.civicrm.org/jira/browse/CRM-9794

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hi, are you applying these same fixes to the d6 branch too?

**Comment by colemanw** [comment]
Oh you're so accommodating Eileen

**Comment by eileenmcnaughton** [comment]
well - breaking d6 code for the sake of removing cruft doesn't make sense to me... (while d6 people might be lessening in number my experience is that they have been among the more significant code / patch / MIH contributors - at least in our stable)

**Comment by colemanw** [comment]
See https://github.com/civicrm/civicrm-drupal/pull/24

**Pull request merged**
