### PR TITLE
dev/drupal#161 Update import of civicrm_generated.mysql to not use th…

### PR DESCRIPTION
**Pull request by seamuslee001**
…e lineMode as per core

This is as per https://github.com/civicrm/civicrm-core/pull/20925 @demeritcowboy @eileenmcnaughton

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I'm going to disagree with this in the sense that as per https://github.com/civicrm/civicrm-core/pull/20925#issuecomment-884645689 it doesn't work with or without this PR and I don't think it ever did. I had posted in chat too but haven't got confirmation or denial yet. My vote would be to remove support for load_generated which brings it in line with the CLI for WP, Joomla, and even Drupal 8. My second-place vote would be to fix up the conditionals so it does work.

**Comment by eileenmcnaughton** [comment]
I endorse removing code that doesn't work as a general principle

**Comment by demeritcowboy** [comment]
Added a suggested note to dev-digest to see if anyone has ever had this working.

**Comment by demeritcowboy** [comment]
Have added https://github.com/civicrm/civicrm-drupal/pull/648 as alternate since nobody has responded to the dev-digest saying they are using it.

**Comment by demeritcowboy** [comment]
Closing since this line doesn't exist anymore.

**Pull request closed without merging**
