### PR TITLE
WIP: CRM-20751: Support Drupal aliases for event links in Views

### PR DESCRIPTION
**Pull request by twomice**
Darn, need to fix civilint errors.

---

 * [CRM-20751: Support Drupal aliases for event links in Views](https://issues.civicrm.org/jira/browse/CRM-20751)

### CODE REVIEW

**Comment by twomice** [comment]
Hi @colemanw I'd like to get your feedback on this please. BTW, there are civilint errors that were already there before; is it preferable for me to clean them up in this PR?

**Comment by colemanw** [comment]
@twomice I'm curious to know why not patch the `civicrm_views_href` and `civicrm_views_url` functions to check drupal path aliases - it's a nice central place to put in this feature.

**Comment by colemanw** [comment]
@twomice for that matter, why not have those functions pass the job off to Drupal and skip the `civicrm_initialize` and `CRM_Utils_` stuff.

**Comment by twomice** [comment]
That would expand the scope to "all of CiviCRM Views" instead of just "Events in Views", but yeah, I'm cool with that. Will give it a try.

**Comment by colemanw** [comment]
Seems like a comfortable middle-ground between "just events in views" 
and "all of CiviCRM core"

**Comment by twomice** [comment]
Jenkins test this please.

**Comment by twomice** [comment]
@colemanw Right, that makes sense. So here it is. This looks right and works for me.

**Comment by colemanw** [comment]
I like it.

**Pull request merged**
