### PR TITLE
Fixed for multi-select filter

### PR DESCRIPTION
**Pull request by pradpnayak**
In latest version of Civi multi-select field is flagged as serialize=1. Since this change was added to CiviCRM module, views failed to filter on multi-select field like multi-select, multi-select country and state. 

@colemanw

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak are you able to rebase this against the rc- I tried just switching it but it has other commits

**Comment by pradpnayak** [comment]
@eileenmcnaughton rebased it

**Comment by eileenmcnaughton** [comment]
Thanks @pradpnayak - I thought you would be in bed!

**Comment by seamuslee001** [comment]
Tested it and agreed this is correct MOP

**Pull request merged**
