### PR TITLE
Add activity created_date, modified_date and original_id fields to views

### PR DESCRIPTION
**Pull request by mattwire**
Add the activity fields created_date, modified_date and original_id to views

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
The functionality of the code looks good, but it looks like you have several lines that have a space at the end of them, and it's throwing some coding style warnings in the tests. Check for that and fix it, and this should be good.

**Comment by mattwire** [comment]
@jackrabbithanna I think the style warnings may be fixed by #526 but I can't tell until it's merged :-)

**Comment by mattwire** [comment]
Jenkins test this please

**Comment by mattwire** [comment]
@jackrabbithanna Tests now passing :-)

**Comment by jackrabbithanna** [comment]
Merging #525

**Pull request merged**
