### PR TITLE
Change PHP keywords to comply with PSR2

### PR DESCRIPTION
**Pull request by mullikine**
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by seamuslee001** [comment]
Hi @mullikine as you will see our style checker picked up on this because we follow the Drupal Coding standards (with some minor changes), their standard is these verbs are in upper case https://www.drupal.org/docs/develop/standards/coding-standards#naming (see under Constants)

**Comment by mullikine** [comment]
> Hi @mullikine as you will see our style checker picked up on this because we follow the Drupal Coding standards (with some minor changes), their standard is these verbs are in upper case https://www.drupal.org/docs/develop/standards/coding-standards#naming (see under Constants)

Interesting! Feel free to discard this PR. If you'd like though, I can retarget this repository with the Drupal standard.

**Comment by totten** [comment]
> Interesting! Feel free to discard this PR. If you'd like though, I can retarget this repository with the Drupal standard.

Cheers, @mullikine. I'll close this PR.

Part of me thinks we should take you up on the offer to validate against Drupal standard, but... that would require a big warning. Strictly speaking, the Civi policy (https://docs.civicrm.org/dev/en/latest/standards/php/) is a *relaxed variant* of the Drupal standard. Symbol-naming conventions are more easy-going (*historical reasons - you can't rename symbols without breaking things*). The PR test bot uses http://github.com/civicrm/coder as the formal implementation of this "relaxed Drupal standard".

Since the overall policy is a bit uncommon, it may not fit well with most tooling, and you may find the process a bit circuitous. OTOH, the code always needs improving - and if you like poking at oddballs, well... here's one. 😃

**Pull request closed without merging**
