### PR TITLE
CRM-16710 : Support for line-items in views integration

### PR DESCRIPTION
**Pull request by Valfr35**
New features for Drupal views integration.
- adding possibility to join contributions to line-items
- adding possibility to join line-items to price and prive-value fields
- adding possibility to join contributions and memberships (two-way) if civiMember and civiContribute are both activated.

(feature previously discussed on CRM-15398)

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks for this pull request!
It would be wonderful if you could rebase out those extra 2 "merge" commits since they make our source tree a bit more confusing. Generally we prefer PRs from a single branch containing one or more commits but no unnecessary merges.

**Comment by Valfr35** [comment]
Ok, I rebase (squash) all commits into one.

**Comment by JKingsnorth** [comment]
The readme.md changes will probably need to be come out of the commit? It's looking good though, I was trying to do this just the other day!

**Comment by Valfr35** [comment]
- The readme file is removed
- 1 commit for adding a relationship from price field to price set".

**Pull request merged**
