### PR TITLE
Adds command to sync users to contacts, useful for thousands of users to...

### PR DESCRIPTION
**Pull request by AronNovak**
... avoid PHP timeout

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mlutfy  - any reason not to merge this?

**Comment by AronNovak** [comment]
Does it make sense to spend time to resolve the conflict? In that case I happily proceed with making it merge-able.

**Comment by colemanw** [comment]
I think this is a good addition. Note that the PR will need to be updated to reflect recent changes in core. The function has been changed from `CRM_Core_BAO_CMSUser::synchronize(FALSE);` to `CRM_Utils_System::synchronizeUsers();`

Note that the new function returns an array of status information, which might be nice to output back to the shell (would require a little parsing - [here's an example](https://github.com/civicrm/civicrm-core/blob/master/CRM/Admin/Form/CMSUser.php#L64-L85) of formatting the output for display).

Aside: the reason you're hitting timeout issues is because the function that performs the syncing is grossly inefficient. But fixing it completely would require the ability to do a sql join between the civi and Drupal databases, which isn't always possible. Ah well.

**Comment by jitendrapurohit** [comment]
cherry-picked this and created a new PR at https://github.com/civicrm/civicrm-drupal/pull/373

**Comment by monishdeb** [comment]
Closed in favour of #373

**Pull request closed without merging**
