### PR TITLE
Event ID contextual filter

### PR DESCRIPTION
**Pull request by yashodha**
expose event ID in Drupal views that are displayed as blocks on event info pages.

### CODE REVIEW

**Comment by yashodha** [comment]
@seamuslee001 Can you check/merge this PR?

**Comment by yashodha** [comment]
@demeritcowboy can you please check this?

**Comment by yashodha** [comment]
@eileenmcnaughton can you please check/merge this?

**Comment by eileenmcnaughton** [comment]
OK - seems safe enough

**Pull request merged**
