### PR TITLE
CRM-19274 Access Instant Messaging in Drupal Views

### PR DESCRIPTION
**Pull request by Vgratioulet**
https://issues.civicrm.org/jira/browse/CRM-19274
In Drupal Views, add a relationship between Contact and Instant Messaging to be able to access the related data

### CODE REVIEW

**Comment by Vgratioulet** [comment]
More location-related relationships changes, details http://civicrm.stackexchange.com/questions/14565/access-instant-messaging-in-drupal-views/14740#14740 and https://issues.civicrm.org/jira/browse/CRM-19258

**Comment by colemanw** [comment]
Code looks good to me. It would be nice to get a user to test it out.

**Comment by colemanw** [comment]
@seamuslee001 has tested out the functionality.

**Comment by JKingsnorth** [comment]
I believe this has caused a regression, reported as: https://issues.civicrm.org/jira/browse/CRM-19740

**Pull request merged**
