### PR TITLE
mysqli

### PR DESCRIPTION
**Pull request by jlillyreed**
Since mysql_connect is deprecated, mysqli should be used instead

### CODE REVIEW

**Comment by xurizaemon** [comment]
This relates to [CRM-17789](https://issues.civicrm.org/jira/browse/CRM-17789)

I am willing to review this PR.

**Comment by colemanw** [comment]
@xurizaemon can you do so early this week so we can get it merged?

**Comment by xurizaemon** [comment]
Seems reviewable. Relates also to CRM-17789 & @civicrm/civicrm-core#8213 etc.

**Comment by JoeMurray** [comment]
Heh Jamil, as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by jlillyreed** [comment]
Hey @JoeMurray I would certainly be up for that

**Comment by JoeMurray** [comment]
@mollux and @jlillyreed could you two collaborate on this PR and #384 ? Thx!

**Comment by seamuslee001** [comment]
@eileenmcnaughton @totten can one of you close this as there was a similar but alternate route that went down to ensure backward compatibility

**Pull request closed without merging**
