### PR TITLE
Bug fix in civicrm.module

### PR DESCRIPTION
**Pull request by albionbrown**
Replaced `$this` with `$edit` in `civicrm_form_data()` when not in object context. 
Ignore the README I made

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Many thanks for the contribution Josh!  Are you able to resubmit (perhaps with a forced rebase) without the README so it's mergeable?  You can do it now or after review takes place.  If you have questions on how to do it, feel free to ask here, or in the ~dev-newcomers channel on https://chat.civicrm.org.  Thanks, and welcome!

**Comment by albionbrown** [comment]
Hi Jon!

I forgot to reply to you yesterday, check the latest commit I think it's
done now (never done a rebase, but I think it's right!).

Josh

**Comment by MegaphoneJon** [comment]
This isn't a rebase, but that's OK - the committer can also deal with it on their end.

For whatever reason it's a little harder to get folks who know this repo to review patches compared to the "civicrm-core" repo, and I'm unfortunately not really qualified here.  I'll work on finding someone.  Thanks again for taking the time.

**Comment by jackrabbithanna** [comment]
How did the problem manifest before this patch? Is there a process that we can follow to replicate the issue and confirm the fix?

**Comment by jackrabbithanna** [comment]
This is a duplicate of https://github.com/civicrm/civicrm-drupal/pull/541/

**Comment by albionbrown** [comment]
Oh sorry I forgot to note how to reproduce! 
 
1. Log into a Drupal user who can administer CiviCRM and Drupal users
2. Find a contact in Civi whose account is not 'linked' to the Drupal account (The user's account has never been logged into and therefore has no record in civicrm_uf_match table to map Civi ID to Drupal User ID)
3. Go to that contact's associated Drupal user page
4. Click on 'Edit'
5. Finally click on 'User Profile'

**Comment by petednz** [comment]
i am seeing this same issue on some contacts where there is a uf_match - and where the Name and Address profile on the /user page does show the civi data - but clicking 'edit Name and Address' throws the error. noting this was a WP site that we moved to Drupal, and cleared out all unwanted uf_match rows and fixed up the remaining ones to work. we are seeing this error on newly created users though as well

**Comment by mlutfy** [comment]
@petednz Can you apply the patch and confirm whether it fixes the issue?

I would still recommend merging #541 instead, because the commit log will be cleaner.

**Comment by eileenmcnaughton** [comment]
#541 merged - closing this as it seems superceded

**Pull request closed without merging**
