### PR TITLE
fix checksum validation in Drupal

### PR DESCRIPTION
**Pull request by mlutfy**
(backport)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton thoughts?

**Comment by eileenmcnaughton** [comment]
Wasn't it just a coding error not a php 7.1 error - ie. no in object context, don't use $this

I'm sure you know I advocate we run CI on php 7.2 which may have helped

**Comment by mlutfy** [comment]
yep, just a programming error. The subject was from the commit I cherry-picked from master.

**Comment by JoeMurray** [comment]
Updated the title of the PR

**Comment by mlutfy** [comment]
Any objections to merging?

**Comment by eileenmcnaughton** [comment]
@mlutfy I merged this & then realised it's against the wrong branch - it should have gone into the rc & any backport to 5.10 would have been discussed on product-maintenance channel after that - anyway I was able to create cleanly against the rc from your branch https://github.com/civicrm/civicrm-drupal/pull/561 - so fixing there

@seamuslee001 @totten  I think it's fine that this hits the security release - I guess it SHOULD have been in yesterday's release but given we missed that & we are so close to next week's release that will prob be OK

**Pull request merged**
