### PR TITLE
Update civicrm.core.inc

### PR DESCRIPTION
**Pull request by callosal**
updated from http://civicrm.stackexchange.com/questions/741/how-do-i-add-civicrm-activity-attachment-to-view/11162?noredirect=1#comment11361_11162

first effort at this so may not be perfect

### CODE REVIEW

**Comment by colemanw** [comment]
There are some minor issues here with code formatting - particuarly comments and whitespace. Check https://www.drupal.org/coding-standards

**Comment by callosal** [comment]
Reviewed this and changed the field that identifies the file_id 

Also , this seems to implicitly link an attachment to activities only.  I don't think this would work for any attachments to entities other than activities

**Comment by JoeMurray** [comment]
@callosal as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by monishdeb** [comment]
@callosal  Is there any Jira (https://issues.civicrm.org/jira/issues) ticket for it ? If not can you create one ? coz this is a nice improvement and should be tracked.

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
Since this stalled a long time back I'm closing to track in gitlab https://lab.civicrm.org/dev/drupal/-/issues/154

**Pull request closed without merging**
