### PR TITLE
CRM-10193 - Allow civicrm-sql-conf and civicrm-sql-cli with empty database

### PR DESCRIPTION
**Pull request by mollux**
[CRM-10193](https://issues.civicrm.org/jira/browse/CRM-10193)

### CODE REVIEW

**Comment by colemanw** [comment]
It looks like this changes drush to never bootstrap Civi - aren't there civi drush commands which depend on this?

**Comment by mollux** [comment]
I think this won't break other functionality, as anywhere where the config is really needed, it will be initialized with the CRM_Core_Config::singleton(); method call.

**Comment by colemanw** [comment]
@totten or @eileenmcnaughton any opinion?

**Comment by eileenmcnaughton** [comment]
I don't know that side of things well enough to comment @torrance  or @xurizaemon might - or @mlutfy

**Comment by jitendrapurohit** [comment]
@mollux While doing QA, I found that the above two commands(civicrm-sql-conf and civicrm-sql-cli) works well with the PR. But the upgrade one errors with the message. Eg:-

```
$ drush civicrm-upgrade-db
DB_DataObject Error: No database name / dsn found anywhere
Drush command terminated abnormally due to an unrecoverable error. 
```

Note : With the bootstrap code in place, it works properly.

**Comment by JoeMurray** [comment]
@jlillyreed this seems related to your #340 - could you consider QAing it? Thx

**Comment by mollux** [comment]
@jitendrapurohit There were indeed some commands that need the loaded config, so I made it optional, with the default to load it.This because most of the commands need the loaded config (only the ones using _civicrm_dsn_init don't need it).

**Comment by jitendrapurohit** [comment]
QA'd the changes. All commands seems to be working fine now :-)

**Pull request merged**
