### PR TITLE
6.x-5.10

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton @totten same again for 6.x

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
for our 11 drupal 6 users...

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
AFAIK the test boxes won't run d6 because d6 can't run on the current php version

**Comment by awasson** [comment]
@seamuslee001 Drupal 6 will run on > PHP 7.1.x with the latest updates. https://github.com/d6lts/drupal/archive/6.49.tar.gz

I maintain several old D6 sites (while they are being migrated) and keep them reasonably safe with the assistance of the MyDropWizard module: https://www.drupal.org/project/mydropwizard

I haven't run one with the latest CiviCRM but I expect it should work.

Andrew

**Comment by totten** [comment]
That's cool to know @awasson. I didn't know that was on github.

@seamuslee001 - yeah, like you, I assumed that PHP version was a constraint. However, I'd say the main reason CI doesn't run on D6 was about more priority (i.e. D6 was already deprecated when we setup jenkins/civibuild). If one really wanted some D6 coverage in `c.o` CI, then we could probably add it to the CiviCRM-E2E-Matrix. Main task would be the build-script, e.g.:

* copy [app/config/drupal-clean](https://github.com/civicrm/civicrm-buildkit/tree/master/app/config) and make `app/config/drupal6-clean`
* edit various version numbers
* (guessing) change [drush dl drupal](https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/drupal-clean/download.sh#L10) to use the d6lts. (it might look cleaner as a `git clone` command...)
* make sure the new build type works

(And, of course, dealing with whatever issues manifest from the new test-coverage.)

**Pull request merged**
