### PR TITLE
Fix Notice: Undefined variable: custom_link in civicrm_handler_field_…

### PR DESCRIPTION
**Pull request by awasson**
Pull request to fix Notice: Undefined variable: custom_link in civicrm_handler_field_link_contact->render_link() (line 118 of civicrm/drupal/modules/views/civicrm/civicrm_handler_field_link_contact.inc). Details of the issue can be found here: https://lab.civicrm.org/dev/drupal/-/issues/168

### CODE REVIEW

**Comment by demeritcowboy** [comment]
jenkins test this please

**Comment by demeritcowboy** [comment]
@awasson It doesn't like the formatting. Click on details to see.

Multiple blank lines and some indentation.

**Comment by demeritcowboy** [comment]
Also see https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive for how to "squash" commits.

**Comment by awasson** [comment]
@demeritcowboy I just saw that. I'm a rookie with PR's so not sure how to proceed. I'll review that link to see how I can fix and repull.

**Comment by awasson** [comment]
@demeritcowboy, I've made a right royal mess of my local and the fork on GitHub. I'm going to close this PR, rebase and give this another try.

**Comment by demeritcowboy** [comment]
Yep that's normal when first doing git stuff. Sometimes best to just start from scratch.

**Pull request closed without merging**
