### PR TITLE
Update civicrm.module links

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
@seamuslee001 replaces https://github.com/civicrm/civicrm-drupal/pull/627

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by totten** [comment]
The test suite is failing on this guard

```bash
case "$ghprbTargetBranch" in
  7.x-4.6*|7.x-4.7*|7.x-5*|7.x-master*)
    CIVIVER=$(echo "$ghprbTargetBranch" | sed 's;^7.x-;;')
    ;;
  *)
    ## This actually true for many branches, so we exit softly...
    echo "PR test not allowed for $ghprbTargetBranch"
    exit 0
    ;;
esac
```

The target branch looks off:

> Screen Shot 2020-11-19 at 9 49 16 PM

Shouldn't the branch be `civicrm:7.x-master`?

**Comment by eileenmcnaughton** [comment]
Yep - that was it

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @totten just realised this still isn't merged

**Pull request merged**
