### PR TITLE
CRM-21371 - An api error when calling drush cvapi should be treated a…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…s a drush error

Also removes an unused var & defines a used var

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
My only concern here is that failing api calls will become 'chattier' and people may have been making use of their existing tendency to fail quietly

**Comment by eileenmcnaughton** [comment]
@mlutfy are you up to merge this - @jmcclelland tested it & commented on JIRA so it has already had some review (I would also contend it's low risk - although I guess there is the question of whether new 'chattiness' would upset some people?)

**Comment by mlutfy** [comment]
I did a bit of testing and seems good to me. I agree with Jamie, the exit code is probably one of the best parts of this.

**Comment by eileenmcnaughton** [comment]
Right - it was the lack of exit code that caused me to dig into it

**Comment by eileenmcnaughton** [comment]
(we weren't noticing fails)

**Pull request merged**
