### PR TITLE
CRM-14707 - Add unit-test for Drupal hook invocation

### PR DESCRIPTION
**Pull request by totten**
- [CRM-14707: Cache function existence in api hooks](https://issues.civicrm.org/jira/browse/CRM-14707)

### CODE REVIEW

**Comment by colemanw** [comment]
@totten is this ready to be merged?

**Comment by totten** [comment]
Kind of. IIRC, the code ran, but there were tooling/process issues (updating Jenkins, dev docs, etc), and I haven't had time to follow-through on that. Merging it won't break anything and may be useful for a couple folks... but I hesitated on merging because it would be mostly inert/undocumented code. For the moment, I've pushed it to "Future Version".

**Comment by totten** [comment]
This was previously hard-coded to a particular directory structure. It's updated now to use the more flexible `cv php:boot` (like the documented approach to extension testing). Also, I've added an example test for the submodule `civicrm_member_roles`.

**Comment by totten** [comment]
Note: This was a non-functional change in that it doesn't modify any live code but adds a new (currently inactive) test-suite. There's a separate TODO for running the tests on our infra.

**Pull request merged**
