### PR TITLE
CRM-12917 - Don't limit number of memberships to sync

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-12917

### CODE REVIEW

**Comment by cravecode** [comment]
Any chance this can get included in the 7.x-4.4 branch? We're on the 4.4LTS and could benefit from this fix.

**Comment by nganivet** [comment]
cravecode - I will do the port, it will hopefully be included in tomorrow's release.

**Comment by eileenmcnaughton** [comment]
I'm happy with that going into the LTS - looks clearcut

**Comment by nganivet** [comment]
Yes, this is why I went ahead and proposed to do the backport. Fix is a one liner with no risk.
The PR is ready at: https://github.com/civicrm/civicrm-drupal/pull/311

cravecode: once the PR is merged by Eileen, would you be able to do some testing and confirm this fixes your issue?

**Comment by eileenmcnaughton** [comment]
@cravecode can you confirm you have tested this on 4.4? It occurred to me the limit of 0 may or may not be respected by 4.4

**Comment by nganivet** [comment]
@eileen yes, limit=0 works in 4.4, verified with the API explorer:
/civicrm/ajax/rest?entity=Membership&action=get&debug=1&sequential=1&json=1&options[limit]=0

**Comment by cravecode** [comment]
@eileenmcnaughton can also confirm, the limit=0 works in 4.4

**Pull request merged**
