### PR TITLE
dev/drupal#193 Replace custom installer with Civi\Setup

### PR DESCRIPTION
**Pull request by mlutfy**
https://lab.civicrm.org/dev/drupal/-/issues/193

Replaces the custom CiviCRM installer by the better-supported `\Civi\Setup`.

This only impacts people still using drush8 (ex: Aegir).

### CODE REVIEW

**Comment by mlutfy** [comment]
Interesting fail:

> E2E\Core\LocalizedDataTest::testLocalizedData The German SQL should match the German pattern.
Failed asserting that false is true.

so I guess we'll be able to see if this PR helps for that fail: https://github.com/civicrm/civicrm-core/pull/29311

**Comment by totten** [comment]
@mlutfy Very nice! 

I did some `r-run` with the patch and had a few small issues. Pushed an update for those.

For my testing, I used these commands:

```bash
## Use second database.  Leave `lang` empty.
drush civicrm-install --dbhost=127.0.0.1:3307 --dbname=dmastercivi_3r007 --dbuser=dmasterciv_4i5or --dbpass=XXX \
        --tarfile=/dev/null -l http://dmaster.127.0.0.1.nip.io:8001 -vv

## Use second database. Set locale to en_US.
drush civicrm-install --dbhost=127.0.0.1:3307 --dbname=dmastercivi_3r007 --dbuser=dmasterciv_4i5or --dbpass=XXX \
        --tarfile=/dev/null -l http://dmaster.127.0.0.1.nip.io:8001 -vv --lang=en_US --langtarfile=/dev/null

## Use second database.  Set locale to fr_FR.
drush civicrm-install --dbhost=127.0.0.1:3307 --dbname=dmastercivi_3r007 --dbuser=dmasterciv_4i5or --dbpass=XXX \
        --tarfile=/dev/null -l http://dmaster.127.0.0.1.nip.io:8001 -vv --lang=fr_FR --langtarfile=/dev/null

## Use single database. Set locale to de_DE.
drush civicrm-install --tarfile=/dev/null -l http://dmaster.127.0.0.1.nip.io:8001 -vv --lang=de_DE --langtarfile=/dev/null

## Use single database.  Leave `lang` empty.
drush civicrm-install --tarfile=/dev/null -l http://dmaster.127.0.0.1.nip.io:8001 -vv 
```

With the patch, they're all working for me. (I didn't test anything that requires downloading a tar file -- but it looks like that stuff wasn't touched by the patch.)

Note: The reported failure (`testLocalizedData`) is pre-existing/unrelated (https://lab.civicrm.org/dev/translation/-/issues/84) and doesn't need to block this PR. If it's working for you, and if the revisions are OK, then +1 for merging.

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
@totten thanks for the testing & fix! 

That translation bug is on my radar too. I don't think it's been fixed?

**Comment by demeritcowboy** [comment]
jenkins retest this please (the localized one should pass now)

**Pull request merged**
