### PR TITLE
CRM-20822 - Expose tag parent id in views

### PR DESCRIPTION
**Pull request by yashodha**
* [CRM-20822: Expose tag parent id in views](https://issues.civicrm.org/jira/browse/CRM-20822)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by yashodha** [comment]
All the fails seems to be indentation for the entire length of the file. Should we merge this first and address that in next PR?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@yashodha can you rebase this please?

**Comment by jackrabbithanna** [comment]
recommend merging this, and the indentation addressed in another PR if you like @yashodha

**Comment by seamuslee001** [comment]
@jackrabbithanna i think the indexing has been fixed in another PR already. I am happy for this to be merged

**Comment by jackrabbithanna** [comment]
Merging #459

**Pull request merged**
