### PR TITLE
CRM-15072 - use contact reference for staff responsible group

### PR DESCRIPTION
**Pull request by jmcclelland**
---
- CRM-15072: staff responsible and event contact fields should be contact reference fields not option groups
  https://issues.civicrm.org/jira/browse/CRM-15072

### CODE REVIEW

**Comment by colemanw** [comment]
Seems like this will need an update script.

**Comment by jmcclelland** [comment]
I think making this a "new sites only" change would be reasonable. I think any kind of modification of existing sites would be too difficult since it would be impossible to map option values (which could just have a first name) with contacts in the database.

**Comment by colemanw** [comment]
Yea that makes sense. Since it's just a custom field should we assume this code change will not break existing sites?

**Comment by jmcclelland** [comment]
Yes - definitely. It is only executed when the user manually goes to the configuration screen and selects the option to add the custom data. The option reads:

Civicrm Engage depends on a number of custom data groups and fields and profiles. Check this box to add them. This step is not reversible and will take several minutes to complete."

There is a check to see if this step has been taken, in which case, the following is added: "It appears that the custom data is present."

And... if someone does it anyway, they'll just get errors about how these custom fields have already been created.

**Pull request merged**
