### PR TITLE
dev/drupal#31 - CiviMember Role sync is no longer syncing Pending mem…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
…berships

To reproduce -

- Create a membership role sync rule with  `ADD WHEN STATUS IS` set to `Pending`.
- Create a membership with pending status.
- Login with the contact and check if the role is assigned.

Before changes - Role is not assigned.
After changes - Role is assigned correctly.

Gitlab Issue - https://lab.civicrm.org/dev/drupal/issues/31

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@spencerbrooks @agh1 either of you interested in reviewing this?

**Comment by spencerbrooks** [comment]
I'm pretty bandwidth-constrained with running my agency these days so I need to pass. @agh1?

**Comment by dyguk** [comment]
This is working fine for us - and very necessary. 
Thanks!

**Comment by eileenmcnaughton** [comment]
merging based on testing by @dyguk - the code also looks pretty sensible & safe

**Pull request merged**
