### PR TITLE
Update docs links

### PR DESCRIPTION
**Pull request by homotechsual**
And replace forum link with SE. Sister PR to civicrm/civicrm-drupal-8#48

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by demeritcowboy** [comment]
This looks good I just have a similar comment to the one for drupal 8 that the reason down on line 216 where this is used isn't the most likely reason anymore. You don't even get this far if civicrm_root is incorrect. A possible reason to hit that line is that CRM/Core/Config.php is missing.

**Comment by homotechsual** [comment]
> This looks good I just have a similar comment to the one for drupal 8 that the reason down on line 216 where this is used isn't the most likely reason anymore. You don't even get this far if civicrm_root is incorrect. A possible reason to hit that line is that CRM/Core/Config.php is missing.

I mean the check that throws this message is a check for CRM/Core/Config.php. Perhaps it's worth rephrasing the actual error message as well?

**Comment by seamuslee001** [comment]
@MikeyMJCO this will need a rebase and its probably more about the language change in the message now as I think Eileen and I have fixed the links based on your feedback

**Comment by homotechsual** [comment]
In which case I'm closing this out. I was only intending to fix the links, not correct the language.

**Comment by homotechsual** [comment]
So I've just picked up what you mean about the language... Not sure why a PR was merged that changes a forum link to SE but leaves the text referencing the community forum??? Not sure why you didn't just merge this PR since it had the links changes AND the text changes...

And this PR wasn't touching the line @demeritcowboy was referencing anyway, so that comment shouldn't have blocked this PR.

**Comment by homotechsual** [comment]
Rebased.

**Comment by demeritcowboy** [comment]
@MikeyMJCO looks like the rebase didn't take?

And yes my comment here was just noting the parallel with the other PR.

**Comment by homotechsual** [comment]
> @MikeyMJCO looks like the rebase didn't take?
> 
> And yes my comment here was just noting the parallel with the other PR.

I'm seeing no conflicts with base branch.

**Comment by homotechsual** [comment]
Force pushed without the extra commit.

**Pull request merged**
