### PR TITLE
Civilint civicrm_og_sync module

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm happy to merge this if you confirm you moved that function without changing it

**Comment by seamuslee001** [comment]
@eileenmcnaughton AFAIK i did not change the function at all

**Comment by eileenmcnaughton** [comment]
OK - that's not quite the confidence I was hoping you would project. I'll have to recreate locally & see

**Comment by seamuslee001** [comment]
@totten @eileenmcnaughton i just did the following

1. Copied the original module file to a new file and deleted all in the new file except for this one function and its docblock
2. Checked out new code and copied to the install to a new file and removed all except the enable function and the docblock 
3. ran diff -ruN originalfile newfile

the diff is as follows So i did touch it but the changes are very minimal

```
--- civicrm_og_sync.module.orig 2017-09-19 06:11:27.557125158 +1000
+++ civicrm_og_sync.module.new  2017-09-19 06:12:02.067862921 +1000
@@ -1,20 +1,19 @@
 <?php
 /**
  * Implemenation of hook_enable.  Use to synchronise with pre-existing groups
- *
- * @return
  */
 function civicrm_og_sync_enable() {
   db_query("UPDATE {system} SET weight = 110 WHERE name = 'civicrm_og_sync'");
-
+
   if (!civicrm_initialize()) {
     return;
   }

   if (function_exists('og_get_group_ids')) {
-  $ogGroupIds = og_get_group_ids('node');
-  } else {
-    $ogGroupIds  =  og_get_all_group('node');
+    $ogGroupIds = og_get_group_ids('node');
+  }
+  else {
+    $ogGroupIds = og_get_all_group('node');
   }

   // FIX ME
@@ -25,7 +24,8 @@
     $node = node_load($gid);
     $title = trim($node->title);
     // length of 49 so that the admin group can fit ': administrator' afterwards within 64 char field
-    $params = array('name' => substr(trim($title), 0, 49),
+    $params = array(
+      'name' => substr(trim($title), 0, 49),
       'title' => $title,
       'is_active' => 1,
       'og_id' => $gid,
```

**Comment by eileenmcnaughton** [comment]
OK -thanks for that! Looks good

**Pull request merged**
