### PR TITLE
Expose CiviAccounts tables relating to Financial Transactions to Views.

### PR DESCRIPTION
**Pull request by ghost**
Exposes civicrm_financial_trxn, civicrm_financial_item, civicrm_financial_account and civicrm_entity_financial_trxn to Views.

### CODE REVIEW

**Comment by mlutfy** [comment]
@agileware  Is this a backport from 4.7? Do you have a JIRA ticket? If not, any chance you could PR this on 4.7 as well?

**Comment by jackrabbithanna** [comment]
FYI You get all of these tables, excepting civicrm_financial_item , exposed out of the box with CiviCRM Entity. 
You also get, LineItem, Price Set Entity, Price Set, Price Field, Price Field Value, MembershipPayment, ParticipantPayment, PaymentProcessor, PaymentProcessorType, PledgePayment, 
I will expose the financial item table as a Drupal entity and put it in the next release...

Lots of the Views relationships are available if you install CiviCRM Entity Views Extras

This could go into 4.6 though for people that don't use that module.

Its been a while @agileware do you still need this in Core?

**Comment by agileware** [comment]
@jackrabbithanna thanks. Just noting also that this PR pre-dates the similar features in CiviCRM Entity by about 12 months. https://www.drupal.org/project/civicrm_entity/releases

civicrm_financial_item is a key table to expose since that was being used for account reporting when this work was done.

Don't mind if this change goes into CiviCRM core or if it makes it's way into CiviCRM Entity. Either way, it would be good for this functionality to be available to the community.

Thanks for taking time to review @jackrabbithanna

**Comment by jackrabbithanna** [comment]
I looked into adding civicrm_financial_item as an exposed Drupal entity, but there's no API for FinancialItem, so the Views integration would have to be "manually" for that table., and not autogenerated by the API metadata.  I may add it to CiviCRM Entity Views Extras.  It doesn't hurt to have this stuff in Core though, as CiviCRM Entity always defers to Core handling if it is available. The exposure's of the Views Extras module would overwrite Core handling, but there's nothing in there that is in Core currently.

**Comment by agileware** [comment]
@jackrabbithanna sounds good to me. We had on our TODO to also submit a PR for 4.7 as well.

**Comment by jackrabbithanna** [comment]
If you make a PR for 4.7, and that gets merged, then I can merge this for 4.6

**Comment by jackrabbithanna** [comment]
Jenkins test this please

**Comment by mlutfy** [comment]
Closing the PR, because it's 1 year old.

**Comment by JoeMurray** [comment]
FWIW, the intent is to have folks use Order API and never create one for financial_item table.

**Pull request closed without merging**
