### PR TITLE
CRM-16479: Support for image styles

### PR DESCRIPTION
**Pull request by JKingsnorth**
- [CRM-16479: Support image styles for contact image in Drupal Views](https://issues.civicrm.org/jira/browse/CRM-16479)

### CODE REVIEW

**Comment by nganivet** [comment]
Joe - I can review this PR since will need to merge it for one of my customers.

**Comment by JKingsnorth** [comment]
Hi @nganivet did you get the chance to review this PR?

**Comment by nganivet** [comment]
John, yes reviewed the code and all seems good. It is also installed on 
one of my production websites and all works well.

------ Original Message ------

**Comment by JKingsnorth** [comment]
Great news, thanks for testing. Can you comment on the JIRA issue too with
the steps you took to test. Hopefully we can get this merged into the next
release then :)

**Comment by houblon** [comment]
Is there supposed to be an interface for this in Views? The code looks like it provides one, but I'm not seeing it. I'm using Drupal 7.52 and CiviCRM 4.7.13, and have installed both the CiviCRM Entities (CiviCRM Entity Views Extras is enabled) and Picture modules. Attached is a screenshot of the Views dialog I get for the CiviCRM Contacts: Contact Image field. Please advise.

If there's a better place to post a question about this, let me know where. Thanks.

civicrm_contact_image_views_dialog

**Comment by JKingsnorth** [comment]
Hi @houblon . The 'Image' module will also need to be enabled. And the CiviCRM images will need to be in the 'public://' files directory in Drupal. The functionality is enabled if 'Image' is enabled, and it can find the right directory (which is handled by this function: https://github.com/civicrm/civicrm-drupal/pull/364/files#diff-141bb1408c66b6d40a72bf7ad9fba3ecR145)

**Comment by houblon** [comment]
Hi @JKingsnorth . Thanks for the quick reply.

I verified that the Image module is enabled (it is; the Picture module requires it), and changed the path settings in the Upload Directories settings of CiviCRM (see attached screenshot), unfortunately with no effect on the Views dialog for the CiviCRM Contacts: Contact Image field. I verified that images uploaded through the CiviCRM contact edit form are uploaded to Drupal's 'public://' files directory.

I also tried changing the CiviCRM Resource URLs path for Image Upload URL to the 'public://' files directory path, but that also didn't have a noticeable effect, and I got an warning that this path shouldn't publicly accessible, so I figure this isn't the path to change.

Is there something else I need to do? Also, for CiviCRM images, is it possible to specify a subdirectory of Drupal's 'public://' files directory?

civicrm_upload_directories_settings

**Comment by magnolia61** [comment]
Works for me using the patched civicrm_handler_field_contact_image.inc
Our configuration: CivCRM 4.7.12 Drupal 7.5.2
civicrm_entity_views_extras: enabled
Image Directory: /home/xyz/domains/ourdomain.nl/public_html/prod/sites/default/files/civicrm/persist/contribute/
Thanks your for this! Will this be included in the 4.7.14 release?

**Comment by houblon** [comment]
@JKingsnorth, I figured it out. I'm using the "CiviCRM 4.7.13 for Drupal 7.x" download from https://civicrm.org/download/list and didn't realize it doesn't include the latest updates for file civicrm_handler_field_contact_image.inc (thanks, @magnolia61, for mentioning that it's currently a patch) . Thanks very much for this functionality; it's working now on my site. As @magnolia61 asked, will this be included in the 4.7.14 release, or should I plan to patch this file for that release?

**Comment by colemanw** [comment]
If you're asking about the patch from this PR, yes it has been merged and will be included in the next release.
If you're talking about a different patch, please advise.

**Pull request merged**
