### PR TITLE
CRM-17652: Symfony conflict between Civi and Drupal 8

### PR DESCRIPTION
**Pull request by dsnopek**
* [CRM-17652: Symfony conflict between Civi and Drupal 8](https://issues.civicrm.org/jira/browse/CRM-17652)

### CODE REVIEW

**Comment by dsnopek** [comment]
Now that https://github.com/civicrm/civicrm-core/pull/10694 is merged, this is the next step to a patchless install on Drupal 8!

**Comment by jackrabbithanna** [comment]
Don't mean to be a stickler but can you fix the spacing before your new if() clause to meet standard Drupal coding standards. 2 less I think :) Big thanks!

**Comment by jackrabbithanna** [comment]
Oh and just remove the lines you commented out please.

**Comment by dsnopek** [comment]
@jackrabbithanna Ah, yes, sorry! I cleaned that bit up. Thinking about it a little more, we should probably update the docs, but I'm not super sure what to put in there since the process is still in flux, and I don't know if it makes sense for the in code docs to be constantly changing too? What do you think?

**Pull request merged**
