### PR TITLE
CRM-19740: Regression in phone number Drupal views integration

### PR DESCRIPTION
**Pull request by Vgratioulet**
Sorry I had two missing files in previous commit to solve https://issues.civicrm.org/jira/browse/CRM-19274

---

 * [    CRM-19759 handles 'require this relationship' for location-related element relationships](https://issues.civicrm.org/jira/browse/CRM-19759)
 * [CRM-19760: add several relationships of the same location-related element](https://issues.civicrm.org/jira/browse/CRM-19760)
 * [CRM-19740: Regression in phone number Drupal views integration](https://issues.civicrm.org/jira/browse/CRM-19740)

### CODE REVIEW

**Comment by Vgratioulet** [comment]
CRM-19274 Views relationships for location-related elements 
I had 2 missing files to make the relationships work in previous commit
Handles now the 'require this relationship' checkbox

**Comment by Vgratioulet** [comment]
should solve https://issues.civicrm.org/jira/browse/CRM-19740

**Comment by monishdeb** [comment]
@Vgratioulet you can squash mutliple commits into one by doing : 
1. ```git rebase -i```
2. it will open vi edit and change ```pick``` to ```squash``` against those commits which you want to squash (means merge commit B with commit A)
3. then save the changes and force push the commit to your origin branch ```git push origin -f CRM-19274-Instant-Messaging-in-Drupal-Views```

**Comment by Vgratioulet** [comment]
@monishdeb thanks, it's more clear indeed

**Review by monishdeb — APPROVED** [review]
Reviewed code and also tested by @JKingsnorth

**Pull request merged**
